### ISSUE TITLE
Error: Cannot find module '/app/safe2pay'

### ISSUE THREAD

**Issue by knoonrx** [SafeToPay/Node#5]
Olá,

Estamos tentando hospedar a API no Heroku, mas está acontecendo o seguinte erro:

```
2020-12-22T23:06:54.967204+00:00 heroku[web.1]: Starting process with command `node index.js`
2020-12-22T23:07:00.002383+00:00 heroku[web.1]: Process exited with status 1
2020-12-22T23:07:00.056599+00:00 heroku[web.1]: State changed from starting to crashed
2020-12-22T23:06:59.909055+00:00 app[web.1]: internal/modules/cjs/loader.js:883
2020-12-22T23:06:59.909076+00:00 app[web.1]:   throw err;
2020-12-22T23:06:59.909077+00:00 app[web.1]:   ^
2020-12-22T23:06:59.909077+00:00 app[web.1]: 
2020-12-22T23:06:59.909077+00:00 app[web.1]: Error: Cannot find module '/app/safe2pay'
2020-12-22T23:06:59.909078+00:00 app[web.1]: Require stack:
2020-12-22T23:06:59.909078+00:00 app[web.1]: - /app/index.js
2020-12-22T23:06:59.909078+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2020-12-22T23:06:59.909079+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2020-12-22T23:06:59.909079+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:952:19)
2020-12-22T23:06:59.909079+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:88:18)
2020-12-22T23:06:59.909080+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:10:18)
2020-12-22T23:06:59.909080+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2020-12-22T23:06:59.909080+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2020-12-22T23:06:59.909081+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:928:32)
2020-12-22T23:06:59.909081+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2020-12-22T23:06:59.909082+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
2020-12-22T23:06:59.909082+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2020-12-22T23:06:59.909082+00:00 app[web.1]:   requireStack: [ '/app/index.js' ]
2020-12-22T23:06:59.909083+00:00 app[web.1]: }
```

**Comment by knoonrx** [comment]
Obrigado à todos pela ajuda :)
